### ISSUE TITLE
Package name clash

### ISSUE THREAD

**Issue by ffaf1** [morganwillcock/kixtart-mode#1]
As an avid KiXtart user, I welcome this!

Unfortunately, I think there is a name clash with [another emacs package](https://melpa.org/#/kixtart-mode) on MELPA.

Users might get confused, maybe you can contact ryrun and team up together?

**Comment by morganwillcock** [comment]
I went through the process to submit the package to the GNU repositories, effectively taking over the MELPA package name (after having arranged this with the author). Unfortunately GNU will not host it because there is no free software interpreter for the scripting language, even though the package itself makes no reference to the interpreter.

I don't use MELPA and so I do not feel motivated to maintain a package through it. I've decided to not publish to any package repository for the time being, removing the name clash at the package repository level. i.e. this package will remain as "manual installation" only.
